# Alur Kerja {#cross}

## Pasien Baru UGD

1. Pasien datang ke UGD
2. Tanyakan keluhan utama
3. Screening TTV dan SpO2
4. Lakukan pemeriksaan anamnesis dan pemeriksaan fisik
5. KIE pemeriksaan penunjang untuk penegakan diagnosis dan KIE waktu tunggu
6. Berikan pengobatan awal dan lakukan pemeriksaan penunjang
7. Konsul ke dr Spesialis terkait jika data cukup
8. Kie pasien dan keluarga terkait diagnosis dan pengobatan yang akan diberikan
9. Berikan pengobatan.

## Pasien rujukan Poli

1. Pasien diantar perawat poli ke UGD.
2. Operan dan baca pengantar rawat inap dari dr Spesialis.
3. Lakukan pemeriksaan anamnesis dan pemeriksaan fisik pasien
4. Konfirmasi instruksi dokter spesialis jika masih ada yang ragu atau kurang.
5. Lakukan pemeriksaan yang diinstruksikan dr Spesialis
6. Berikan pengobatan yang diinstruksikan dr Spesialis
7. Konsulkan hasil pemeriksaan penunjang ke dr Spesialis

## Pasien Pre-OP

1. Pasien diantar keluarga ke UGD
2. Tanyakan keluhan utama, jika dikatakan rencana operasi.
3. Tanyakan pengantar rawat inap
4. Lakukan pemeriksaan anamnesis dan pemeriksaan fisik pasien
5. Konfirmasi instruksi dokter spesialis DPJP jika masih ada yang ragu atau kurang.
6. Lakukan pemeriksaan yang diinstruksikan DPJP
7. Berikan pengobatan yang diinstruksikan DPJP
8. Konsulkan hasil pemeriksaan penunjang ke DPJP
9. Lakukan konsul ke dr Spesialis lain jika diinstruksikan DPJP
10. Jika semua dr spesialis sudah acc tindakan atau semua instruksi telah dilakukan, konsul anestesi
11. Sampaikan hasil konsul dr anestesi ke DPJP