# Poli Umum, Visite dan Rujukan

## Poli Umum
Poli Umum merupakan layanan rawat jalan bagi pasien yang ingin melakukan pemeriksaan general (non spesialistik) atau pemeriksaan penunjang khusus tanpa membawa pengantar pemeriksaan. Pasien yang ingin melakukan pemeriksaan general biasanya tidak mengetahui gejalanya mengarah ke penyakit mana, maka memerlukan pemeriksaan dokter umum. Pasien yang ingin melakukan check-up dengan pemeriksaan penunjang tanpa membawa pengantar sebelumnya dapat melalui poli umum dan berkonsultasi dengan dokter umum. Dokter umum di poli umum diisi oleh dokter jaga. Petugas poli akan menghubungi dokter jaga jika ada pasien umum daftar di loket poli lantai 1. Semua pembiayaan di poli umum ditanggung pasien/asuransi swasta.

Pemeriksaan dilakukan berdasarkan setting pemeriksaan rawat jalan. Pemeriksaan akan didampingi oleh 1-2 orang perawat poliklinik. Pemeriksaan dapat dilakukan di Lt 1 dengan menggunakan ruang poli yang kosong, atau di UGD. Dokter dapat memberikan saran pemeriksaan penunjang yang tersedia di RS dengan persetujuan pasien. Pemeriksaan laboratorum kimiawi serta radiologi non-usg tanpa persiapan khusus hasil dapat diperoleh dalam hitungan 30 menit-jam. Pemeriksaan USG hanya dapat dilakukan pada sore-malam pada hari kerja sehingga dapat diberikan pengantar dan daftar saja untuk USG dan instruksikan pasien datang ke RS pada waktu layanan USG ada di RS. Pemeriksaan radiologi atau lab dengan persiapan khusus diperlukan KIE terkait persiapan dengan baik. Tentukan waktu pasien untuk ke RS kembali dengan membawa pengantar unuk melakukan pemeriksaan setelah persiapan sekiranya terpenuhi. 

## Visite
Visite dilakukan jika dokter spesialis DPJP berhalangan untuk melakukan visite rutin atau terdapat kondisi tertentu dimana diperlukan pemeriksaan dokter kepada pasien diluar waktu visite dokter spesialis, sebagai contoh perburukan kondisi pasien atau muncul gejala akut tambahan. Keperluan visite akan diinformasikan oleh perawat ruangan. 

Pemeriksaan saat visite dilakukan berdasarkan seting pemeriksaan rawata inap. Pasca pemeriksaan, dokter menulis SOAP di bagian CPPT (catatan perkembangan pasien terintegrasi). Jika terdapat perkembangan pasien yang memerlukan pelaporan ke DPJP, maka dapat menghubungi DPJP. Tuliskan instruksi DPJP di lembar CPPT dan berikan stempel Tulbakon.

Terkait perekapan pasien visite, dokter jaga dapat mengisi excel di komputer kanan IGD. Catat nama, no rekam medik, diagnosis, tanggal visite serta kelas rawat (Kelas BPJS, eksekutif dll) 

## Rujukan
### Menerima Rujukan

Rujukan biasanya datang dari RS tipe D dan Puskesmas. Saat dihubungi perhatikan informasi mengenai:

* Identitas 
* Kelas Perawatan
* Tanda Vital dan Klinis
* Kebutuhan perawatan
* Skrining COVID-19
* Mohon mengirimkan data pasien dalam format SOAP

**Sebelum menerima rujukan pastikan:**

**1. Pasien transportable**

* Vital sign dan klinis stabil untuk perjalanan ke Rumah Sakit.
* Terpasang alat bantu seperti iv line dan oksigen jika diperlukan

**2. Skrining COVID-19 yang telah dilakukan**

* Gejala klinis ISPA/Respirasi yang mengarah ke COVID-19
* Riwayat vaksin COVID-19
* Hasil skrining Rapid Test Antigen COVID-19
* Apakah bisa dilakukan chest xray di fasker perujuk, jika bisa minta lakukan dulu.

**3. Hubungi ranap terkait apakah terdapat ketersediaan ruangan dan fasilitasnya**

* Hubungi ruangan yang akan menjadi tempat perawatan pasien untuk mengetahui ketersediaan Bed sesuai kelas rawat. Jika kelas rawat sesuai hak di RS penuh, makan akan dititipkan ke kelas rawat dibawahnya hingga terdapat bed sesuai hak kelas rawat pasien. 
* Perkirakan kebutuhan pasien saat perawatan, misal ventilator. Jika menggunakan ruangan ICU dan membutuhkan ventilator tanya ke ruang ICU terkait ketersediaan bed icu dan ventilator. Contoh lain, bayi neonatus membutuhkan infant warmer, tanyakan ke PICU terkait ketersediaannya.
* Rumah Sakit saat ini belum memiliki layanan HD, HCU, ruang intensif Isolasi dan ventilator untuk bayi.

**4. Perkirakan apakah kasus pasien dapat diterapi di rumah sakit kita**

* Bagian terpenting adalah memastikan apakah pasien akan dapat ditatalaksana di Rumah Sakit kita.
* Jika ragu dapat dilakukan konsultasi terhadap DPJP jaga di RS (mengirimkan SOAP pasien) atau MOD (dr Adi)

### Melakukan Perujukan

**1. Lakukan pemeriksaan pasien**

* Ketahui keadaan terkini pasien
* Pastikan transportable, jika ragu hubungi kembali DPJP pemberi instruksi rujukan.

**2. Siapkan berkas-berkas dan pelajari catatan perkembangan pasien dan ketik SOAP.**

**3. Hubungi Admisi RS tujuan rujukan** 

* Sampaikan tujuan rujukan dan diagnosis
* Sampaikan kebutuhan perawatan pasien, misalnya ruangan biasa/isolasi, kelas perawatan, kebutuhan ICU dan ventilator.

**4. Komunikasi dengan dokter Jaga RS tujuan**

* Sampaikan SOAP dan alasan perujukan
* Tunggu acc dokter jaga (biasanya dikonsulkan juga ke DPJP Terkait RS Tujuan)

**5. Komunikasi ke petugas ruangan**

* Jika diinstruksikan oleh dokter jaga untuk komunikasi ke petugas ruangan untuk mengetahui keadaan pasien (rujukan ke ruang isolasi atau ruang intensif isolasi)

**6. Komunikasikan keberangkatan pasien**

* Berikan informasi ke dokter jaga RS Tujuan jika pasien sudah siap untuk dikirim dari RS.

#### Persiapan Rujukan Khusus 
##### HD CITO
Untuk rujukan ke RS lain yang bisa melakukan HD cito, maka perlu ditanyakan apakah dilakukan pemeriksaa HBSAG di RS kita sebelum dirujuk. Jika pasien sudah pernah di periksa HBSAG, maka data tersebut bisa dipersiapkan dan disampaikan saat komunikasi dengan dr Jaga RS Rujukan.

